modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="potionenchant"
version="${mod_version}"
displayName="Potionenchant"
logoFile="potion.png"
authors="Diexv"
description='''Potionenchant is a mod that adds custom enchantments to Minecraft.'''

[[dependencies.potionenchant]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.potionenchant]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.potionenchant]]
    modId="curios"
    mandatory=false
    versionRange="[5.0,)"
    ordering="NONE"
    side="BOTH"
