package net.diexv.potionenchant.util;

import java.util.HashMap;
import java.util.Map;

public class PinyinHelper {

    private static final Map<Character, String> PINYIN_MAP = new HashMap<>();

    static {
        PINYIN_MAP.put('\u4E00', "yi");
        PINYIN_MAP.put('\u4E07', "wan");
        PINYIN_MAP.put('\u4E0A', "shang");
        PINYIN_MAP.put('\u4E0B', "xia");
        PINYIN_MAP.put('\u4E0D', "bu");
        PINYIN_MAP.put('\u4E0E', "yu");
        PINYIN_MAP.put('\u4E14', "qie");
        PINYIN_MAP.put('\u4E24', "liang");
        PINYIN_MAP.put('\u4E2A', "ge");
        PINYIN_MAP.put('\u4E2D', "zhong");
        PINYIN_MAP.put('\u4E3A', "wei");
        PINYIN_MAP.put('\u4E45', "jiu");
        PINYIN_MAP.put('\u4E4B', "zhi");
        PINYIN_MAP.put('\u4E5F', "ye");
        PINYIN_MAP.put('\u4E8E', "yu");
        PINYIN_MAP.put('\u4E92', "hu");
        PINYIN_MAP.put('\u4EA1', "wang");
        PINYIN_MAP.put('\u4EA4', "jiao");
        PINYIN_MAP.put('\u4EA7', "chan");
        PINYIN_MAP.put('\u4EB2', "qin");
        PINYIN_MAP.put('\u4EBA', "ren");
        PINYIN_MAP.put('\u4ECE', "cong");
        PINYIN_MAP.put('\u4ED6', "ta");
        PINYIN_MAP.put('\u4EE5', "yi");
        PINYIN_MAP.put('\u4F1A', "hui");
        PINYIN_MAP.put('\u4F24', "shang");
        PINYIN_MAP.put('\u4F46', "dan");
        PINYIN_MAP.put('\u4F4D', "wei");
        PINYIN_MAP.put('\u4F4E', "di");
        PINYIN_MAP.put('\u4F53', "ti");
        PINYIN_MAP.put('\u4F60', "ni");
        PINYIN_MAP.put('\u4F7F', "shi");
        PINYIN_MAP.put('\u4F8B', "li");
        PINYIN_MAP.put('\u4F9B', "gong");
        PINYIN_MAP.put('\u4FDD', "bao");
        PINYIN_MAP.put('\u4FEE', "xiu");
        PINYIN_MAP.put('\u500D', "bei");
        PINYIN_MAP.put('\u503C', "zhi");
        PINYIN_MAP.put('\u50A8', "chu");
        PINYIN_MAP.put('\u5143', "yuan");
        PINYIN_MAP.put('\u5146', "zhao");
        PINYIN_MAP.put('\u5149', "guang");
        PINYIN_MAP.put('\u514B', "ke");
        PINYIN_MAP.put('\u514D', "mian");
        PINYIN_MAP.put('\u5176', "qi");
        PINYIN_MAP.put('\u5185', "nei");
        PINYIN_MAP.put('\u518D', "zai");
        PINYIN_MAP.put('\u51B2', "chong");
        PINYIN_MAP.put('\u51B6', "ye");
        PINYIN_MAP.put('\u51B7', "leng");
        PINYIN_MAP.put('\u51C0', "jing");
        PINYIN_MAP.put('\u51CB', "diao");
        PINYIN_MAP.put('\u51CF', "jian");
        PINYIN_MAP.put('\u51FA', "chu");
        PINYIN_MAP.put('\u51FB', "ji");
        PINYIN_MAP.put('\u5206', "fen");
        PINYIN_MAP.put('\u5229', "li");
        PINYIN_MAP.put('\u5230', "dao");
        PINYIN_MAP.put('\u523A', "ci");
        PINYIN_MAP.put('\u5242', "ji");
        PINYIN_MAP.put('\u524D', "qian");
        PINYIN_MAP.put('\u529B', "li");
        PINYIN_MAP.put('\u52A0', "jia");
        PINYIN_MAP.put('\u52A8', "dong");
        PINYIN_MAP.put('\u52B3', "lao");
        PINYIN_MAP.put('\u5316', "hua");
        PINYIN_MAP.put('\u5347', "sheng");
        PINYIN_MAP.put('\u534A', "ban");
        PINYIN_MAP.put('\u5355', "dan");
        PINYIN_MAP.put('\u5373', "ji");
        PINYIN_MAP.put('\u5374', "que");
        PINYIN_MAP.put('\u539F', "yuan");
        PINYIN_MAP.put('\u53BB', "qu");
        PINYIN_MAP.put('\u53CD', "fan");
        PINYIN_MAP.put('\u53D1', "fa");
        PINYIN_MAP.put('\u53D6', "qu");
        PINYIN_MAP.put('\u53D7', "shou");
        PINYIN_MAP.put('\u53EF', "ke");
        PINYIN_MAP.put('\u540C', "tong");
        PINYIN_MAP.put('\u540E', "hou");
        PINYIN_MAP.put('\u5438', "xi");
        PINYIN_MAP.put('\u547C', "hu");
        PINYIN_MAP.put('\u547D', "ming");
        PINYIN_MAP.put('\u548C', "he");
        PINYIN_MAP.put('\u54C1', "pin");
        PINYIN_MAP.put('\u55B7', "pen");
        PINYIN_MAP.put('\u56F4', "wei");
        PINYIN_MAP.put('\u5723', "sheng");
        PINYIN_MAP.put('\u5728', "zai");
        PINYIN_MAP.put('\u574F', "huai");
        PINYIN_MAP.put('\u5757', "kuai");
        PINYIN_MAP.put('\u575A', "jian");
        PINYIN_MAP.put('\u578B', "xing");
        PINYIN_MAP.put('\u57FA', "ji");
        PINYIN_MAP.put('\u589E', "zeng");
        PINYIN_MAP.put('\u5904', "chu");
        PINYIN_MAP.put('\u590D', "fu");
        PINYIN_MAP.put('\u5916', "wai");
        PINYIN_MAP.put('\u591C', "ye");
        PINYIN_MAP.put('\u5927', "da");
        PINYIN_MAP.put('\u5931', "shi");
        PINYIN_MAP.put('\u59CB', "shi");
        PINYIN_MAP.put('\u5A01', "wei");
        PINYIN_MAP.put('\u5B50', "zi");
        PINYIN_MAP.put('\u5B58', "cun");
        PINYIN_MAP.put('\u5B8C', "wan");
        PINYIN_MAP.put('\u5B9A', "ding");
        PINYIN_MAP.put('\u5B9E', "shi");
        PINYIN_MAP.put('\u5BB3', "hai");
        PINYIN_MAP.put('\u5BB6', "jia");
        PINYIN_MAP.put('\u5BD2', "han");
        PINYIN_MAP.put('\u5BF9', "dui");
        PINYIN_MAP.put('\u5C04', "she");
        PINYIN_MAP.put('\u5C06', "jiang");
        PINYIN_MAP.put('\u5C11', "shao");
        PINYIN_MAP.put('\u5C3D', "jin");
        PINYIN_MAP.put('\u5C55', "zhan");
        PINYIN_MAP.put('\u5CA9', "yan");
        PINYIN_MAP.put('\u5DE6', "zuo");
        PINYIN_MAP.put('\u5E27', "zhen");
        PINYIN_MAP.put('\u5E38', "chang");
        PINYIN_MAP.put('\u5E45', "fu");
        PINYIN_MAP.put('\u5E76', "bing");
        PINYIN_MAP.put('\u5E78', "xing");
        PINYIN_MAP.put('\u5E84', "zhuang");
        PINYIN_MAP.put('\u5EA6', "du");
        PINYIN_MAP.put('\u5EF6', "yan");
        PINYIN_MAP.put('\u5F00', "kai");
        PINYIN_MAP.put('\u5F31', "ruo");
        PINYIN_MAP.put('\u5F53', "dang");
        PINYIN_MAP.put('\u5F84', "jing");
        PINYIN_MAP.put('\u5F97', "de");
        PINYIN_MAP.put('\u6001', "tai");
        PINYIN_MAP.put('\u6025', "ji");
        PINYIN_MAP.put('\u6027', "xing");
        PINYIN_MAP.put('\u6028', "yuan");
        PINYIN_MAP.put('\u603B', "zong");
        PINYIN_MAP.put('\u6062', "hui");
        PINYIN_MAP.put('\u6069', "en");
        PINYIN_MAP.put('\u60E0', "hui");
        PINYIN_MAP.put('\u6162', "man");
        PINYIN_MAP.put('\u6210', "cheng");
        PINYIN_MAP.put('\u6216', "huo");
        PINYIN_MAP.put('\u6240', "suo");
        PINYIN_MAP.put('\u6269', "kuo");
        PINYIN_MAP.put('\u6297', "kang");
        PINYIN_MAP.put('\u62A4', "hu");
        PINYIN_MAP.put('\u62DB', "zhao");
        PINYIN_MAP.put('\u62E5', "yong");
        PINYIN_MAP.put('\u6301', "chi");
        PINYIN_MAP.put('\u6309', "an");
        PINYIN_MAP.put('\u6316', "wa");
        PINYIN_MAP.put('\u6325', "hui");
        PINYIN_MAP.put('\u635F', "sun");
        PINYIN_MAP.put('\u6377', "jie");
        PINYIN_MAP.put('\u6398', "jue");
        PINYIN_MAP.put('\u63A5', "jie");
        PINYIN_MAP.put('\u63D0', "ti");
        PINYIN_MAP.put('\u6536', "shou");
        PINYIN_MAP.put('\u653B', "gong");
        PINYIN_MAP.put('\u653E', "fang");
        PINYIN_MAP.put('\u6548', "xiao");
        PINYIN_MAP.put('\u654C', "di");
        PINYIN_MAP.put('\u654F', "min");
        PINYIN_MAP.put('\u6570', "shu");
        PINYIN_MAP.put('\u65B9', "fang");
        PINYIN_MAP.put('\u65E0', "wu");
        PINYIN_MAP.put('\u65F6', "shi");
        PINYIN_MAP.put('\u660E', "ming");
        PINYIN_MAP.put('\u6613', "yi");
        PINYIN_MAP.put('\u661F', "xing");
        PINYIN_MAP.put('\u662F', "shi");
        PINYIN_MAP.put('\u666E', "pu");
        PINYIN_MAP.put('\u6697', "an");
        PINYIN_MAP.put('\u66B4', "bao");
        PINYIN_MAP.put('\u66F4', "geng");
        PINYIN_MAP.put('\u6700', "zui");
        PINYIN_MAP.put('\u6709', "you");
        PINYIN_MAP.put('\u672A', "wei");
        PINYIN_MAP.put('\u6751', "cun");
        PINYIN_MAP.put('\u6765', "lai");
        PINYIN_MAP.put('\u679C', "guo");
        PINYIN_MAP.put('\u6807', "biao");
        PINYIN_MAP.put('\u680F', "lan");
        PINYIN_MAP.put('\u683C', "ge");
        PINYIN_MAP.put('\u6982', "gai");
        PINYIN_MAP.put('\u6B21', "ci");
        PINYIN_MAP.put('\u6B62', "zhi");
        PINYIN_MAP.put('\u6B64', "ci");
        PINYIN_MAP.put('\u6B7B', "si");
        PINYIN_MAP.put('\u6BCF', "mei");
        PINYIN_MAP.put('\u6BD2', "du");
        PINYIN_MAP.put('\u6BD4', "bi");
        PINYIN_MAP.put('\u6C34', "shui");
        PINYIN_MAP.put('\u6CBB', "zhi");
        PINYIN_MAP.put('\u6CD5', "fa");
        PINYIN_MAP.put('\u6D01', "jie");
        PINYIN_MAP.put('\u6D46', "jiang");
        PINYIN_MAP.put('\u6D6E', "fu");
        PINYIN_MAP.put('\u6D77', "hai");
        PINYIN_MAP.put('\u6D88', "xiao");
        PINYIN_MAP.put('\u6D8C', "yong");
        PINYIN_MAP.put('\u6DFB', "tian");
        PINYIN_MAP.put('\u6E05', "qing");
        PINYIN_MAP.put('\u6E85', "jian");
        PINYIN_MAP.put('\u6EDE', "zhi");
        PINYIN_MAP.put('\u6EE1', "man");
        PINYIN_MAP.put('\u6F02', "piao");
        PINYIN_MAP.put('\u6F6E', "chao");
        PINYIN_MAP.put('\u706B', "huo");
        PINYIN_MAP.put('\u706D', "mie");
        PINYIN_MAP.put('\u70B8', "zha");
        PINYIN_MAP.put('\u70B9', "dian");
        PINYIN_MAP.put('\u70BC', "lian");
        PINYIN_MAP.put('\u70C8', "lie");
        PINYIN_MAP.put('\u70EC', "jin");
        PINYIN_MAP.put('\u7126', "jiao");
        PINYIN_MAP.put('\u7130', "yan");
        PINYIN_MAP.put('\u7206', "bao");
        PINYIN_MAP.put('\u7269', "wu");
        PINYIN_MAP.put('\u72B6', "zhuang");
        PINYIN_MAP.put('\u7387', "lv");
        PINYIN_MAP.put('\u73A9', "wan");
        PINYIN_MAP.put('\u751F', "sheng");
        PINYIN_MAP.put('\u7532', "jia");
        PINYIN_MAP.put('\u7559', "liu");
        PINYIN_MAP.put('\u7597', "liao");
        PINYIN_MAP.put('\u75AB', "yi");
        PINYIN_MAP.put('\u75B2', "pi");
        PINYIN_MAP.put('\u767E', "bai");
        PINYIN_MAP.put('\u7684', "de");
        PINYIN_MAP.put('\u76D4', "kui");
        PINYIN_MAP.put('\u76EE', "mu");
        PINYIN_MAP.put('\u76F8', "xiang");
        PINYIN_MAP.put('\u7740', "zhe");
        PINYIN_MAP.put('\u77AC', "shun");
        PINYIN_MAP.put('\u77E2', "shi");
        PINYIN_MAP.put('\u7834', "po");
        PINYIN_MAP.put('\u7840', "chu");
        PINYIN_MAP.put('\u788E', "sui");
        PINYIN_MAP.put('\u7965', "xiang");
        PINYIN_MAP.put('\u79BB', "li");
        PINYIN_MAP.put('\u79D2', "miao");
        PINYIN_MAP.put('\u79FB', "yi");
        PINYIN_MAP.put('\u7A7A', "kong");
        PINYIN_MAP.put('\u7A7F', "chuan");
        PINYIN_MAP.put('\u7B49', "deng");
        PINYIN_MAP.put('\u7BAD', "jian");
        PINYIN_MAP.put('\u7C92', "li");
        PINYIN_MAP.put('\u7D20', "su");
        PINYIN_MAP.put('\u7EA6', "yue");
        PINYIN_MAP.put('\u7EA7', "ji");
        PINYIN_MAP.put('\u7EC6', "xi");
        PINYIN_MAP.put('\u7EC8', "zhong");
        PINYIN_MAP.put('\u7ECF', "jing");
        PINYIN_MAP.put('\u7EED', "xu");
        PINYIN_MAP.put('\u7F13', "huan");
        PINYIN_MAP.put('\u7F6E', "zhi");
        PINYIN_MAP.put('\u8010', "nai");
        PINYIN_MAP.put('\u8017', "hao");
        PINYIN_MAP.put('\u805A', "ju");
        PINYIN_MAP.put('\u80C3', "wei");
        PINYIN_MAP.put('\u80F8', "xiong");
        PINYIN_MAP.put('\u80FD', "neng");
        PINYIN_MAP.put('\u8106', "cui");
        PINYIN_MAP.put('\u81EA', "zi");
        PINYIN_MAP.put('\u81F4', "zhi");
        PINYIN_MAP.put('\u82E5', "ruo");
        PINYIN_MAP.put('\u82F1', "ying");
        PINYIN_MAP.put('\u8303', "fan");
        PINYIN_MAP.put('\u836F', "yao");
        PINYIN_MAP.put('\u83B7', "huo");
        PINYIN_MAP.put('\u84C4', "xu");
        PINYIN_MAP.put('\u865A', "xu");
        PINYIN_MAP.put('\u8679', "hong");
        PINYIN_MAP.put('\u8840', "xue");
        PINYIN_MAP.put('\u884C', "xing");
        PINYIN_MAP.put('\u8865', "bu");
        PINYIN_MAP.put('\u8870', "shuai");
        PINYIN_MAP.put('\u88AB', "bei");
        PINYIN_MAP.put('\u89C4', "gui");
        PINYIN_MAP.put('\u89C6', "shi");
        PINYIN_MAP.put('\u89E3', "jie");
        PINYIN_MAP.put('\u89E6', "chu");
        PINYIN_MAP.put('\u8BA1', "ji");
        PINYIN_MAP.put('\u8BA4', "ren");
        PINYIN_MAP.put('\u8BB0', "ji");
        PINYIN_MAP.put('\u8BE5', "gai");
        PINYIN_MAP.put('\u8C5A', "tun");
        PINYIN_MAP.put('\u8D1F', "fu");
        PINYIN_MAP.put('\u8D77', "qi");
        PINYIN_MAP.put('\u8D85', "chao");
        PINYIN_MAP.put('\u8DC3', "yue");
        PINYIN_MAP.put('\u8DDD', "ju");
        PINYIN_MAP.put('\u8DF3', "tiao");
        PINYIN_MAP.put('\u8E2A', "zong");
        PINYIN_MAP.put('\u8EAB', "shen");
        PINYIN_MAP.put('\u8F6C', "zhuan");
        PINYIN_MAP.put('\u8F7D', "zai");
        PINYIN_MAP.put('\u8FBE', "da");
        PINYIN_MAP.put('\u8FC7', "guo");
        PINYIN_MAP.put('\u8FD0', "yun");
        PINYIN_MAP.put('\u8FDB', "jin");
        PINYIN_MAP.put('\u8FDE', "lian");
        PINYIN_MAP.put('\u8FEB', "po");
        PINYIN_MAP.put('\u8FFD', "zhui");
        PINYIN_MAP.put('\u901A', "tong");
        PINYIN_MAP.put('\u901F', "su");
        PINYIN_MAP.put('\u9020', "zao");
        PINYIN_MAP.put('\u91CA', "shi");
        PINYIN_MAP.put('\u91CD', "zhong");
        PINYIN_MAP.put('\u91CF', "liang");
        PINYIN_MAP.put('\u94F8', "zhu");
        PINYIN_MAP.put('\u94FE', "lian");
        PINYIN_MAP.put('\u9501', "suo");
        PINYIN_MAP.put('\u950B', "feng");
        PINYIN_MAP.put('\u952E', "jian");
        PINYIN_MAP.put('\u957F', "zhang");
        PINYIN_MAP.put('\u95F4', "jian");
        PINYIN_MAP.put('\u9632', "fang");
        PINYIN_MAP.put('\u963B', "zu");
        PINYIN_MAP.put('\u9644', "fu");
        PINYIN_MAP.put('\u964D', "jiang");
        PINYIN_MAP.put('\u9650', "xian");
        PINYIN_MAP.put('\u9664', "chu");
        PINYIN_MAP.put('\u9690', "yin");
        PINYIN_MAP.put('\u96C4', "xiong");
        PINYIN_MAP.put('\u96EA', "xue");
        PINYIN_MAP.put('\u96F6', "ling");
        PINYIN_MAP.put('\u9700', "xu");
        PINYIN_MAP.put('\u9709', "mei");
        PINYIN_MAP.put('\u9762', "mian");
        PINYIN_MAP.put('\u989D', "e");
        PINYIN_MAP.put('\u98D8', "piao");
        PINYIN_MAP.put('\u9965', "ji");
        PINYIN_MAP.put('\u9971', "bao");
        PINYIN_MAP.put('\u997F', "e");
        PINYIN_MAP.put('\u9A8C', "yan");
        PINYIN_MAP.put('\u9AD8', "gao");
        PINYIN_MAP.put('\u9B54', "mo");
        PINYIN_MAP.put('\u9ED1', "hei");
        PINYIN_MAP.put('\u9ED8', "mo");
        PINYIN_MAP.put('\u9F20', "shu");
        PINYIN_MAP.put('\u9F50', "qi");
    }

    public static String toPinyin(String text) {
        if (text == null || text.isEmpty()) return "";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            String py = PINYIN_MAP.get(c);
            if (py != null) {
                if (sb.length() > 0) sb.append(" ");
                sb.append(py);
            }
        }
        return sb.toString();
    }

    public static String toPinyinInitials(String text) {
        if (text == null || text.isEmpty()) return "";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            String py = PINYIN_MAP.get(c);
            if (py != null && !py.isEmpty()) {
                sb.append(py.charAt(0));
            }
        }
        return sb.toString();
    }

    public static boolean matchesSearch(String text, String chineseName, String englishName, String resourceId, String searchLower) {
        if (searchLower == null || searchLower.isEmpty()) return true;
        if (text == null) text = ""; if (chineseName == null) chineseName = "";
        if (englishName == null) englishName = ""; if (resourceId == null) resourceId = "";
        String lower = text.toLowerCase();
        String cnLower = chineseName.toLowerCase();
        String enLower = englishName.toLowerCase();
        String idLower = resourceId.toLowerCase();
        if (lower.contains(searchLower) || cnLower.contains(searchLower) || enLower.contains(searchLower) || idLower.contains(searchLower)) return true;
        String pinyin = toPinyin(chineseName);
        if (pinyin.contains(searchLower) || pinyin.replace(" ", "").contains(searchLower)) return true;
        String initials = toPinyinInitials(chineseName);
        if (initials.contains(searchLower)) return true;
        if (pinyin.replace(" ", "").contains(searchLower.replace(" ", ""))) return true;
        return false;
    }
}
